# Generated by Django 4.2.8 on 2024-01-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_transformerdata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformerLocationData',
            fields=[
                ('devUID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
