# Generated by Django 4.2.8 on 2024-01-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_transformerlocationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformerlocationdata',
            name='operational',
            field=models.BooleanField(default=True),
        ),
    ]
