# Generated by Django 4.2.8 on 2024-01-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_transformerlocationdata_operational'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformerdata',
            name='current_loading_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transformerlocationdata',
            name='nominal_power_rating',
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
