# Generated by Django 4.2.8 on 2024-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_transformerdata_current_loading_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformerdata',
            name='nominal_power_rating',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
