# Generated by Django 4.2.8 on 2024-01-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_transformerdata_nominal_power_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformerdata',
            name='output_current',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transformerdata',
            name='output_frequency',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transformerdata',
            name='output_power',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transformerdata',
            name='output_reactive_power',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transformerdata',
            name='output_voltage',
            field=models.FloatField(default=0),
        ),
    ]
